import = ["~/.config/alacritty/solarized-osaka/solarized-osaka.toml"]

[env]
TERM = "xterm-256color"

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "buttonless"
option_as_alt = "OnlyLeft"
