theme = "base16_transparent"

[editor]
popup-border = "all"
auto-info = false

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[keys.normal]
C-g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]
